#!/bin/bash

declare -A app
app['path']='/app/xge'
app['appname']='xge'
app['color']='bg-color-blue'
app['db.pass']='hjedvtht'
app['db.user']='KNL_USER'
app['ico']='icon-chart'
app['name']='Carbon XGE Router 5'
app['path']='/app/xge'
app['ppp-server.ip']='10.0.201.1'
app['ppp-server.ip.widget']='ip "IP-адрес VPN-серверов" "Не забудьте продублировать в network"'
app['widget']='menu "Настройки маршрутизатора"'

declare -A vpn
vpn['pptp.enabled']='1'
vpn['pptp.enabled.widget']='1'='checkbox "Включить поддержку PPTP" ""'
vpn['pppoe.enabled']='1'
vpn['pppoe.enabled.widget']='1'='checkbox "Включить поддержку PPPoE" ""'
vpn['l2tp.enabled']='1'
vpn['l2tp.enabled.widget']='1'='checkbox "Включить L2TP" ""'
vpn['auth.pap']='1'
vpn['auth.pap.widget']='1'='checkbox "Включить PAP-авторизацию" ""'
vpn['auth.chap_md5']='1'
vpn['auth.chap_md5.widget']='1'='checkbox "Включить CHAP (md5) авторизацию" ""'
vpn['auth.mschap1']='1'
vpn['auth.mschap1.widget']='1'='checkbox "Включить MS-CHAP v1" ""'
vpn['auth.mschap2']='1'
vpn['auth.mschap2.widget']='1'='checkbox "Включить MS-CHAP v2" ""'

declare -A network
network['widget']='menu "Настройка сети" "Настройка сети"'

#общие для всех интерфейсов виджеты
network['if.widget']='table "Настройка интерфейсов" "Настройки интерфейса: ip/mask, gate"'
network['if']=''
network['if.ip.widget']='inputbox "IP адрес интерфейса" "IP адрес интерфейса и маска, формат 10.90.140.10/24"'
network['if.name.widget']='inputbox "Имя интерфейса" "Имя интерфейса, например Внешний интерфейс"'
network['if.gate.widget']='inputbox "IP адрес шлюза" "IP адрес шлюза, например 10.0.0.1"'
network['if.disabled.widget']='checkbox "Отключить интерфейс" "Включить/выключить интерфейс"'
network['if.device.widget']='interface_list "Физический интерфейс" "Физический интерфейс, например eth0/eth1"'
network['if.brd.widget']='inputbox "Бродкаст адрес" "Необходимо только для vlan"'
network['if.tag.widget']='inputbox "Тэг vlan" "Необходимо только для vlan"'
network['if.role.widget']='radiolist "Роль интерфейса" "External - внешний, Local - внутренний"'
network['if.role.list']='"External" "Внешний" "Для доступа к вышестоящему провайдеру" "Local" "Внутренний" "Для подключений абонентов"'

#if 0
network['if0.brd']=''
network['if0.device']='dummy0'
network['if0.disabled']='0'
network['if0.gate']=''
network['if0.ip']='10.0.201.1'
network['if0.name']='Интерфейс для VPN'
network['if0.role']='Local'
network['if0.tag']=''
network['if0.type']='ethernet'
network['if0.vlan']='0'

declare -A firewall
firewall['enabled']='1'
firewall['enabled.widget']='checkbox "Включить файрвол" ""'
firewall['new_limit_l']='2000'
firewall['new_limit_l.widget']='inputbox "Ограничить колво новых соед/сек из лок.сети" "Рекомендуется 500-1000"'
firewall['new_limit_e']='2000'
firewall['new_limit_e.widget']='inputbox "Ограничить колво новых соед/сек из Интернет" "Рекомендуется 500-1000"'

declare -A remote_management
remote_management['widget']='menu "Настройки управления маршрутизатором" "Пароль задаётся в настройках Radius"'
remote_management['carbon_nasd.enabled.widget']='checkbox "Включить демон приёма команд от биллинга" "Без него XGE-Router не будет корректно работать"'
remote_management['carbon_nasd.enabled']='1'
remote_management['carbon_coad.enabled.widget']='checkbox "Включить обработчик radius coa" "Без него XGE-Router не будет корректно работать"'
remote_management['carbon_coad.enabled']='1'

declare -A nfusens
nfusens['widget']='menu "Настройки сенсора netflow" ""'
nfusens['enabled.widget']='checkbox "Включить nfusens" "Без него XGE-Router не будет корректно работать"'
nfusens['enabled']='1'

declare -A radclient
radclient['widget']='menu "Настройки Radius" "Настройки подключения к биллингу (АСР / ААА-серверу)"'
radclient['secret']='123'
radclient['netflow_collector']='10.0.0.254:9996'
radclient['netflow_collector.widget']='inputbox "Сервер сборки статистики" "Адрес netflow-коллектора: IP:PORT"'
radclient['secret.widget']='inputbox "Radius-secret" "Секретный ключ для доступа к биллингу (АСР / ААА-серверу)"'
radclient['authserver']='10.0.0.254:1812'
radclient['authserver.widget']='inputbox "Сервер авторизации" "Сервер авторизации, формат: IP:PORT"'
radclient['acctserver']='10.0.0.254:1813'
radclient['acctserver.widget']='inputbox "Сервер аккаунтинга" "Сервер аккаунтинга, формат: IP:PORT"'
radclient['nas_identifier']='10.0.0.10'
radclient['nas_identifier.widget']='inputbox "IP адрес этого NAS-сервера" "Является идентификатором этого AS в настройках Radius-сервера биллинга"'

declare -A ctl
ctl['start']='/service start'
ctl['stop']='/service stop'
ctl['status']='/service status'

declare -A mount
mount['proc']='-t proc none /app/xge/proc'
mount['dev']='-t devtmpfs none /app/xge/dev'
