#!/bin/bash
# chkconfig: - 81 15
# description: Main worker

. /etc/rc.d/init.d/functions
. /cfg/config

ALREADY_RUN=111
RETVAL=1
prog="Carbon Netflow Sensor"
PROG="nfusens"
LOCKFILE="/var/lock/subsys/$PROG"

start() {
	[ "${nfusens['enabled']}" = '1' ] || exit 255
	echo -n $"Starting $prog: "
	[ -s /var/run/$PROG.pid ] && return 0
	/usr/local/sbin/$PROG -a "${nfusens['collector']%%:*}" -p "${nfusens['collector']##*:}" -d >> /var/log/$PROG.log 2>&1
	RETVAL=$?
	touch $LOCKFILE
	[ "$RETVAL" != "0" ] && rm -f $LOCKFILE /var/run/$PROG.pid
	return $RETVAL
}

stop() {
	[ "${nfusens['enabled']}" = '1' ] || exit 255
	echo -n $"Stopping $prog: "
	# killproc $PROG 2>/dev/null
	[ -s /var/run/$PROG.pid ] && kill  $(</var/run/$PROG.pid)
	RETVAL=$?
	rm -f $LOCKFILE /var/run/$PROG.pid
	return $RETVAL
}

# See how we were called.
case "$1" in
	start)
		start
		RETVAL=$?
		[ "$RETVAL" = "0" ] && echo_success || echo_failure
		;;
	stop)
		stop
		RETVAL=$?
		[ "$RETVAL" = "0" ] && echo_success || echo_failure
		;;
	restart)
		[ "${nfusens['enabled']}" = '1' ] || exit 255
		stop && echo_success || echo_failure
		echo
		start 
		RETVAL=$?
		[ "$RETVAL" = '0' ] && echo_success || echo_failure
		;;
	condrestart)
		[ -e "$LOCKFILE" ] && restart
		RETVAL=$?
		;;
	status)
		status $proc
		RETVAL=$?
		;;
	*)  
		echo $"Usage: $0 {start|stop|status|restart|condrestart}"
		exit 1
		;;
esac
echo 
exit $RETVAL
