#!/bin/bash

CONFIG=/cfg/config
. $CONFIG

genconfig() {
	while IFS= read -r line; do
		if [ "${line:0:1}" = "#"  ]; then
			echo "$line"
			continue
		fi      
		while [[ "$line" = *@@@*%%%* ]]; do
			VARNAME=""
			VARNAME="${line#*@@@}"
			VARNAME="${VARNAME%%%%%*}"
			VARVALUE=""
			[ "$VARNAME" != "" ] && eval VARVALUE="\$$VARNAME"
			line="${line//@@@$VARNAME%%%/$VARVALUE}"
		done
		echo "$line"
	done < $tmpltfile >$conffile
}

gen_radius_config() {
	# radiusclient и servers
	acctserver="${radclient[acctserver]}"
	authserver="${radclient[authserver]}"
	server_ip=${authserver%%:*}
	secret="${radclient[secret]}"
	nas_identifier="${radclient[nas_identifier]}"

	conffile=/etc/radiusclient/servers
	tmpltfile=/etc/radiusclient/servers.tmplt

	genconfig

	conffile=/etc/radiusclient/radiusclient.conf
	tmpltfile=/etc/radiusclient/radiusclient.conf.tmplt

	genconfig
}

gen_hosts_file() {
	app_ip=${app[ppp-server-ip]%%/*}
	host_name=$(hostname)
	conffile=/etc/hosts
	tmpltfile=/etc/hosts.tmplt

	genconfig
}

gen_accel_pppd_config() {
	conffile=/etc/accel-ppp.conf
	tmpltfile=/etc/accel-ppp.conf.tmplt
	[ "${vpn['pptp.enabled']}" = '1' ] && pptp_string=pptp
	[ "${vpn['pppoe.enabled']}" = '1' ] && pppoe_string=pppoe
	[ "${vpn['l2tp.enabled']}" = '1' ] && l2tp_string=l2tp
	[ "${vpn['auth.pap']}" = '1' ] && pap_string=auth_pap
	[ "${vpn['auth.chap_md5']}" = '1' ] && chap_md5_string=auth_chap_md5
	[ "${vpn['auth.mschap1']}" = '1' ] && mschap1_string=auth_mschap_v1
	[ "${vpn['auth.mschap2']}" = '1' ] && mschap2_string=auth_mschap_v2
	ppp_server_ip=${app['server_ip']}

	genconfig
}

main() {
	gen_accel_pppd_config
	gen_radius_config
	gen_hosts_file
}

main $@
