#!/bin/bash

CONFIG=/cfg/config
. $CONFIG

genconfig() {
	while IFS= read -r line; do
		if [ "${line:0:1}" = "#"  ]; then
			echo "$line"
			continue
		fi
		while [[ "$line" = *@@@*%%%* ]]; do
			VARNAME=""
			VARNAME="${line#*@@@}"
			VARNAME="${VARNAME%%%%%*}"
			VARVALUE=""
			[ "$VARNAME" != "" ] && eval VARVALUE="\$$VARNAME"
			line="${line//@@@$VARNAME%%%/$VARVALUE}"
		done
		echo "$line"
	done < $tmpltfile >$conffile
}

gen_radius_config() {
	# radiusclient и servers
	acctserver="${radclient['acctserver']}"
	authserver="${radclient['authserver']}"
	server_ip=${authserver%%:*}
	secret="${radclient['secret']}"
	nas_identifier="${radclient['nas_identifier']}"
	coa_client_ip="${radclient['coa_client.ip']}"
	coa_server_port="${radclient['coa_server.port']:-3799}"
	coa_client_passwd="${radclient['coa_client.passwd']}"

	conffile=/etc/radiusclient/servers
	tmpltfile=/skelet/etc/radiusclient/servers.tmplt
	genconfig

	conffile=/etc/radiusclient/radiusclient.conf
	tmpltfile=/skelet/etc/radiusclient/radiusclient.conf.tmplt
	genconfig

	conffile=/etc/raddb/radiusd.conf
	tmpltfile=/skelet/etc/raddb/radiusd.conf.tmplt
	genconfig

	conffile=/etc/raddb/clients.conf
	tmpltfile=/skelet/etc/raddb/clients.conf.tmplt
	genconfig
}

gen_hosts_file() {
	app_ip=${app[ppp-server.ip]%%/*}
	host_name=$(hostname)
	conffile=/etc/hosts
	tmpltfile=/skelet/etc/hosts.tmplt

	genconfig
}

gen_accel_pppd_config() {
	conffile=/etc/accel-ppp.conf
	tmpltfile=/skelet/etc/accel-ppp.conf.tmplt
	acctserver="${radclient[acctserver]}"
	authserver="${radclient[authserver]}"
	acctserver_ip=${acctserver%%:*}
	acctserver_port=${acctserver##*:}
	authserver_ip=${authserver%%:*}
	authserver_port=${authserver##*:}
	server_ip=${authserver%%:*}
	secret="${radclient[secret]}"
	nas_identifier="${radclient[nas_identifier]}"
	ppp_server_ip=${app['ppp-server.ip']}

	[ "${vpn['pptp.enabled']}" = '1' ] && pptp_string=pptp
	[ "${vpn['pppoe.enabled']}" = '1' ] && pppoe_string=pppoe
	[ "${vpn['l2tp.enabled']}" = '1' ] && l2tp_string=l2tp
	[ "${vpn['auth.pap']}" = '1' ] && pap_string=auth_pap
	[ "${vpn['auth.chap_md5']}" = '1' ] && chap_md5_string=auth_chap_md5
	[ "${vpn['auth.mschap1']}" = '1' ] && mschap1_string=auth_mschap_v1
	[ "${vpn['auth.mschap2']}" = '1' ] && mschap2_string=auth_mschap_v2

	genconfig
}

gen_httpd_config() {
	conffile=/etc/httpd/conf/httpd.conf
	tmpltfile=/skelet/etc/httpd/conf/httpd.conf.tmplt

	internal_httpd_ip_port=${httpd['internal_ip']}:80
	redirect_httpd_ip_port=${httpd['redirect_ip']}:80
	noauth_httpd_ip_port=${httpd['redirect_noauth_ip']}:80
	webauth_httpd_ip_port=${httpd['redirect_webauth_ip']}:80

	for i in internal_ip redirect_ip redirect_noauth_ip redirect_webauth_ip; do
		ip addr add ${httpd[$i]}/8 dev dummy0
	done &>/dev/null
	genconfig

	# redirect part
	URL="${httpd['redirect_page']}"
	conffile="/var/www/html/redirect/.htaccess"
	tmpltfile="/var/www/html/redirect/.htaccess.tmplt"
	genconfig

	# noauth part
	URL="${httpd['redirect_noauth_page']}"
	conffile="/var/www/html/noauth/.htaccess"
	tmpltfile="/var/www/html/noauth/.htaccess.tmplt"
	genconfig

	# webauth part
	URL="${httpd['redirect_webauth_page']}"
	conffile="/var/www/html/webauth/.htaccess"
	tmpltfile="/var/www/html/webauth/.htaccess.tmplt"
	genconfig

	authserver="${radclient[authserver]}"
	auth_port=${authserver##*:}
	server=${authserver%%:*}
	secret="${radclient[secret]}"
	users_psw="${radclient[users_psw]}"
	conffile="/var/www/html/noauth/noauth.php"
	tmpltfile="/var/www/html/noauth/noauth.php.tmplt"
	genconfig
}


main() {
	gen_httpd_config
	gen_accel_pppd_config
	gen_radius_config
	gen_hosts_file
}

main $@
