#!/bin/bash

start() {
	/genconfig
	/usr/local/bin/firewall start
	/etc/init.d/carbon_nasd start
	echo "TODO: pptpd as init"
	/usr/local/sbin/pptpd --delegate
	#openl2tpd
	#pppoe-server
	#carbon_nasd
	#nfusens
	#named
	#quagga
}

stop() {
	/usr/local/bin/firewall stop
	/etc/init.d/carbon_nasd stop
	echo "TODO: pptpd as init"
	killall pptpd
	return 0
}

restart() {
	stop
	start
}

$1
