#!/bin/bash --noprofile

. /cfg/config

echo 50000000 > /proc/sys/net/core/rmem_default
spooldir=/var/spool/xge/cmd
PROG=/usr/local/bin/nas_cmd5

log() {
	echo "$(date +"%Y-%m-%d %H:%M:%S") $HOSTNAME ${0##*/}[$$]: $@"
}

while true; do
	for cmd in $spooldir/*; do
		log processing $cmd $(<$cmd)
		$PROG $(<$cmd) || log failed $cmd $(<$cmd)
		rm -f $cmd
	done

	find -type f /var/spool/xge/cmd/ &>/dev/null || sleep 1
done
