#!/bin/bash --noprofile

. /cfg/config

echo 50000000 > /proc/sys/net/core/rmem_default
spooldir=/var/spool/xge/cmd
PROG=/usr/local/bin/nas_cmd5

log() {
	echo "$(date +"%Y-%m-%d %H:%M:%S") $HOSTNAME ${0##*/}[$$]: $@"
}

wait_for_files() {
	while ! [ -f /var/spool/xge/cmd/* ]; do
		sleep 1
	done
}

main() {
	while true; do
		wait_for_files
		for cmd in $spooldir/*; do
			log processing $cmd $(<$cmd)
			$PROG $(<$cmd) || log failed $cmd $(<$cmd)
			rm -f $cmd
		done
	done
}

main $@
