#!/bin/bash

export PATH=$PATH:/usr/local/bin/:/usr/local/sbin/
mkdir -p /var/run/xge_auth/
mkdir -p /var/run/xge_auth_bad/

while true; do
	[ ! -f /var/run/xge_auth/radattr.* ] && sleep 1 && echo -n .  && continue
	for file in /var/run/xge_auth/radattr.*; do
		if ! /usr/local/bin/ip-up.ip ${file#*.}; then
			echo "$(date +"%Y-%m-%d %H:%M:%S") $HOSTNAME ${0##*/}[$$]: $file bad"
			mv $file /var/run/xge_auth_bad/
		else
			echo "$(date +"%Y-%m-%d %H:%M:%S") $HOSTNAME ${0##*/}[$$]: $file ok"
			rm -f $file
		fi
	done
done
